#######################################################################################
# Book settings
title : QSS 20. Modern Statistical Computing
author: Jaren Haber
logo: 'laptop.png'

# Information about where the book exists on the web
description: >-
  This repository houses the code for the Jupyter Book for QSS20: Modern Statistical Computing, a course in the Quantitative Social Science program at Dartmouth College. This course is taught by Jaren Haber.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/executablebooks/quantecon-mini-example
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
